### ISSUE TITLE
package.json?

### ISSUE THREAD

**Issue by xshotD** [memework/memework-official-bot#1]
should be implemented for proper practices and for easier installs of the bot.

**Comment by jaacks** [comment]
i mean its only one dep

**Comment by nullpixel1** [comment]
But still, it's only npm init and npm install --save

**Comment by jaacks** [comment]
you have a point
@motiontheking fix it

**Comment by motiontheking** [comment]
one dep
i dont need
a
motherfucking
package
.
j
s
o
n

**Comment by motiontheking** [comment]
fine u tards
